### ISSUE TITLE
Travis set up on fork repo disabled coveralls? 

### ISSUE THREAD

**Issue by olwend** [makersacademy/airport_challenge#682]
I wasnt sure where to open this - it is more general config than airport challenge specific.

Following the contributing.md guidelines I set up Travis CI on my repo
https://github.com/olwend/airport_challenge
https://travis-ci.org/olwend/airport_challenge

It appears to be running rspec tests but has disabled Coveralls and coverage is showing at 100% across board.
1.  errors on coveralls (below from https://s3.amazonaws.com/archive.travis-ci.org/jobs/190061421/log.txt) 
I've no idea how to set the repo in coveralls - Travis link API?? I've googled and checked travis.yml from this repo.. still no progress.

Can you tell me how to reinstate coveralls? 

Thanks

`__{"message":"Couldn't find a repository matching this job.","error":true}[0m__`

`
[33m[Coveralls] Submitting with config:[0m
[33m{
  "environment": {
    "pwd": "/home/travis/build/olwend/airport_challenge",
    "rails_root": null,
    "simplecov_root": "/home/travis/build/olwend/airport_challenge",
    "gem_version": "0.7.9",
    "travis_job_id": "190061421",
    "travis_pull_request": "false"
  },
  "git": {
    "head": {
      "id": "b3a479e9c3429c327607364f9eea44ba50010396",
      "author_name": "olwend",
      "author_email": "olwend@gmail.com",
      "committer_name": "olwend",
      "committer_email": "olwend@gmail.com",
      "message": "Errors for airport stormy or full added"
    },
    "branch": "(detached from b3a479e)",
    "remotes": [
      {
        "name": "origin",
        "url": "https://github.com/olwend/airport_challenge.git"
      }
    ]
  },
  "service_job_id": "190061421",
  "service_name": "travis-ci"
}[0m
[36m[Coveralls] Submitting to https://coveralls.io/api/v1[0m
[31mCoveralls encountered an exception:[0m
[31mRestClient::UnprocessableEntity[0m
[31m422 Unprocessable Entity[0m
[31m/home/travis/build/olwend/airport_challenge/vendor/bundle/ruby/2.2.0/gems/rest-client-1.7.2/lib/restclient/abstract_response.rb:48:in `return!'[0m
[31m/home/travis/build/olwend/airport_challenge/vendor/bundle/ruby/2.2.0/gems/rest-client-1.7.2/lib/restclient/request.rb:495:in `process_result'[0m
[31m/home/travis/build/olwend/airport_challenge/vendor/bundle/ruby/2.2.0/gems/rest-client-1.7.2/lib/restclient/request.rb:421:in `block in transmit'[0m
[31m/home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:853:in `start'[0m
[31m/home/travis/build/olwend/airport_challenge/vendor/bundle/ruby/2.2.0/gems/rest-client-1.7.2/lib/restclient/request.rb:413:in `transmit'[0m
[31m/home/travis/build/olwend/airport_challenge/vendor/bundle/ruby/2.2.0/gems/rest-client-1.7.2/lib/restclient/request.rb:176:in `execute'[0m
[31m/home/travis/build/olwend/airport_challenge/vendor/bundle/ruby/2.2.0/gems/rest-client-1.7.2/lib/restclient/request.rb:41:in `execute'[0m
[31m/home/travis/build/olwend/airport_challenge/vendor/bundle/ruby/2.2.0/gems/coveralls-0.7.9/lib/coveralls/api.rb:24:in `post_json'[0m
[31m/home/travis/build/olwend/airport_challenge/vendor/bundle/ruby/2.2.0/gems/coveralls-0.7.9/lib/coveralls/simplecov.rb:72:in `format'[0m
[31m/home/travis/build/olwend/airport_challenge/vendor/bundle/ruby/2.2.0/gems/simplecov-0.9.1/lib/simplecov/result.rb:46:in `format!'[0m
[31m/home/travis/build/olwend/airport_challenge/vendor/bundle/ruby/2.2.0/gems/simplecov-0.9.1/lib/simplecov/configuration.rb:158:in `block in at_exit'[0m
[31m/home/travis/build/olwend/airport_challenge/vendor/bundle/ruby/2.2.0/gems/simplecov-0.9.1/lib/simplecov/defaults.rb:54:in `call'[0m
[31m/home/travis/build/olwend/airport_challenge/vendor/bundle/ruby/2.2.0/gems/simplecov-0.9.1/lib/simplecov/defaults.rb:54:in `block in <top (required)>'[0m
[31m{"message":"Couldn't find a repository matching this job.","error":true}[0m

travis_time:end:002a9c5a:start=1483906666931429255,finish=1483906667759212351,duration=827783096
[0K
[32;1mThe command "bundle exec rspec spec" exited with 0.[0m

Done. Your build exited with 0.`

**Comment by olwend** [comment]
I have now seen Coveralls is working locally, as there is a change

[Coveralls] Outside the CI environment, not sending data.
[Coveralls] Some handy coverage stats:
  * lib/Airport.rb => 100%
  * lib/Plane.rb => 90%
  * spec/airport_spec.rb => 100%
  * spec/feature_spec.rb => 100%
  * spec/plane_spec.rb => 100%
